ci: Created separate test for the containers in frontend and backend test.yml

diff --git a/backend/test.yml b/backend/test.yml
--- a/backend/test.yml
+++ b/backend/test.yml
@@ -13,3 +13,32 @@ backend-test:
     - cd backend/Volunti
     - dotnet restore
     - dotnet test --configuration Release
+
+backend-container-test:
+  stage: test-container
+  image: docker:latest
+  rules:
+    - exists:
+      - backend/Dockerfile
+  variables:
+    IMAGE_TAG: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
+    CONTAINER_NAME: test-backend-$CI_JOB_ID
+  script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - docker pull $IMAGE_TAG
+    - docker run -d --name $CONTAINER_NAME -P $IMAGE_TAG
+    - HOST_PORT=$(docker port $CONTAINER_NAME 8080/tcp | cut -d: -f2)
+    - |
+      for time in $(seq 1 30); do 
+        if docker exec test-container curl -sf http://localhost:8080/swagger/index.html >/dev/null 2>&1; then
+          echo "Backend responding after: ${time} seconds" 
+          docker stop test-container
+          exit 0
+        fi
+        sleep 2
+      done
+      echo "Backend: Container test failure"
+      docker logs $CONTAINER_NAME
+      exit 1
+  after_script:
+    - docker rm -f $CONTAINER_NAME || true
diff --git a/frontend/test.yml b/frontend/test.yml
--- a/frontend/test.yml
+++ b/frontend/test.yml
@@ -5,3 +5,32 @@ frontend-test:
     - cd frontend/Volunti.Web
     - npm ci
     - npm run test -- --run
+
+frontend-container-test:
+  stage: test-container
+  image: docker:latest
+  rules:
+    - exists:
+      - frontend/Dockerfile
+  variables:
+    IMAGE_TAG: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
+    CONTAINER_NAME: test-frontend-$CI_JOB_ID
+  script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+    - docker pull $IMAGE_TAG
+    - docker run -d --name $CONTAINER_NAME -P $IMAGE_TAG
+    - HOST_PORT=$(docker port $CONTAINER_NAME 80/tcp | head -1 | cut -d: -f2
+    - |
+      for time in $(seq 1 30); do
+        if curl -sf http://localhost:${HOST_PORT}/ >/dev/null 2>&1; then
+          echo "Frontend: Running after ${time} seconds"
+          docker stop test-frontend
+          exit 0
+        fi
+        sleep 5
+      done
+      echo "Frontend: Container test failed"
+      docker logs $CONTAINER_NAME
+      exit 1
+  after_script:
+    - docker rm -f $CONTAINER_NAME || true
